---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner1
  namespace: gitlab
data:
  config.toml: |
    concurrent = 4
    check_interval = 0

    [session_server]
      session_timeout = 1800

    [[runners]]
      name = "Kubernetes Runner"
      url = "https://gitlab/"
      token = "TOKEN"
      executor = "shell"
